### ISSUE TITLE
No exports from module

### ISSUE THREAD

**Issue by ReadyPlayerNaN** [byuarchdi/print-headers-and-footers#3]
Hi, I'm trying to do import/require on your module, but it does not provide anything. Could you please do `module.exports` for node environment?

**Comment by lastmjs** [comment]
Would you mind implementing it? It seems easy enough, you've got the environment set up and can verify that it works. It would be appreciated

**Comment by lastmjs** [comment]
Of course I don't think we should break compatibility for people who are using the global object as well.

**Comment by lastmjs** [comment]
I'm thinking something at the bottom like:

```
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
    module.exports = PrintHAF;
}
```

**Comment by ReadyPlayerNaN** [comment]
I suggest using an already existing pattern, like this one: https://github.com/umdjs/umd/blob/master/templates/commonjsStrict.js

**Comment by lastmjs** [comment]
@just-paja I appreciate the contribution, thanks again!
